application/routes/generate_deck.py
"""
    This file contains all views for generating a deck.
"""

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, jsonify
)
from flask_login import login_required, current_user

from application.handlers import Cardhandler, Deckhandler
from application.gpt import gpt_generate_deck
from application.engine import pdf_reader
from application.engine.handle_markdown import markdown_to_html

# Create blueprint for deck views
bp = Blueprint('generate_deck', __name__)

""" ---------- Helpers ---------- """

def dict_to_deck(deck_dict, user):
    """ Create a deck from a dict. Returns deck id """
    name = deck_dict.get('name')
    desc = deck_dict.get('description')
    questions = deck_dict.get('questions')
    answers = deck_dict.get('answers')
    deck_id = Deckhandler.add_deck(name, desc, user)
    Cardhandler.create_cards(questions, answers, deck_id)
    return deck_id

def get_extension(filename: str) -> str:
    return filename.rsplit('.', 1)[1].lower()

def is_pdf(filename: str) -> bool:
    if not '.' in filename: return False
    return get_extension(filename) == 'pdf'

def is_markdown(filename: str) -> bool:
    if not '.' in filename: return False
    return get_extension(filename) == 'md'

def is_txt(filename: str) -> bool:
    if not '.' in filename: return False
    return get_extension(filename) == 'txt'

""" ---------- Routes ---------- """

@bp.route('/generate_deck/deck_from_file/', methods=('GET', 'POST'))
@login_required
def deck_from_file():
    # Get input
    file = request.files['file']
    n_cards = int(request.form.get('n_cards'))
    prompt = request.form.get('prompt')
    start_page = int(request.form.get('start-page'))
    end_page = int(request.form.get('end-page'))
    # Decode file content
    if is_pdf(file.filename):
        text = pdf_reader.extract_text(file, start_page, end_page)
    elif is_markdown(file.filename) or is_txt(file.filename):
        file_content = file.read()
        text = file_content.decode('utf-8')
    else:
        flash('Invalid file')
        return redirect(url_for('generate_deck.from_file'))
    # Generate deck
    raw_deck = gpt_generate_deck(text, n_cards, [prompt])
    if not raw_deck:
        flash('There was an error trying to generate your deck.')
        return redirect(url_for('decks.index'))
    deck_id = Deckhandler.add_deck(name=raw_deck.get('name'), description=raw_deck.get('description'), user=current_user)
    for question, answer in zip(raw_deck.get('questions'), raw_deck.get('answers')):
        # Convert markdown to html
        if is_markdown(file.filename):
            question = markdown_to_html(question)
            answer = markdown_to_html(answer)
        Cardhandler.add_card(question, answer, deck_id)
    return redirect(url_for('decks.index'))

@bp.route('/generate_deck/number_of_pdf_pages', methods=['POST'])
def get_number_of_pdf_pages():
    # Check if request correct with file
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400
    # Check if file selected
    file = request.files['file']
    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400
    # Get page range if is pdf
    if file and is_pdf(file.filename):
        page_range = pdf_reader.get_page_range(file)
        return jsonify({"page_range": page_range})
    return jsonify({"error": "Not pdf"}), 400

@bp.route('/generate_deck/cards_from_desc/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def cards_from_desc(deck_id):
    # Save deck
    name = request.form.get('name')
    description = request.form.get('description')
    Deckhandler.update_deck(name, description, deck_id)
    # Generate cards
    raw_deck = gpt_generate_deck(description)
    if not raw_deck:
        flash('There was an error trying to generate your cards.')
        return redirect(url_for('deck_editor.deck_editor', deck_id=deck_id))
    for question, answer in zip(raw_deck.get('questions'), raw_deck.get('answers')):
        Cardhandler.add_card(question, answer, deck_id)
    
    deck = Deckhandler.get_deck(deck_id)
    return redirect(url_for('deck_editor.deck_editor', deck_id=deck.id))

@bp.route('/generate_deck/from_prompt')
@login_required
def from_prompt():
    return render_template('/generate_deck/from_prompt.html')

@bp.route('/generate_deck/from_file')
@login_required
def from_file():
    return render_template('generate_deck/from_file.html')

@bp.route('/generate_deck/generate_deck_begin', methods=('GET', 'POST'))
@login_required
def generate_deck_begin():
    quantities = {
        'few': 10,
        'medium': 25,
        'many': 50
    }
    prompt = request.form.get('prompt')
    focus_areas = request.form.getlist('focus_areas')
    quantity = request.form.get('quantity')
    n_cards = quantities[quantity]
    raw_deck = gpt_generate_deck(prompt, n_cards, focus_areas)
    if not raw_deck:
        flash('There was an error trying to generate your deck.')
        return redirect(url_for('decks.index'))
    deck_id = dict_to_deck(raw_deck, current_user)
    flash('Deck generated successfully')
    return redirect(url_for('deck_editor.deck_editor', deck_id=deck_id))

application/templates/generate_deck/from_file.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Generate deck{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="deck-page">
    <div class="newdeck-editor-box-outer">
      <div class="newdeck-editor-box" id="file-generator-view">
        <form class="generate-form" action="{{ url_for('generate_deck.deck_from_file') }}" method="post" enctype="multipart/form-data">
          <h2>Generate deck from File</h2>
          <div class="file-drop-box" id="file-drop-box">
            <h3>Drag & drop file here or click to select a file</h3>
            <p id="uploaded-file-name">no file selected</p>
            <input type="file" id="fileElem" name="file" accept=".txt, .md, .pdf" onchange="handleFile(this.files)" hidden required>
            <label class="secondary-button" for="fileElem">Select a file</label>
            <p>Files supported: .pdf, .txt, .md</p>
          </div>
          <div id="n-pages-box" class="n-pages-box">
            <p>Page range</p>
            <!-- <label for="start-page">From</label> -->
            <input type="number" id="start-page" name="start-page" min="1" max="1" value="1">
            <label for="end-page">-</label>
            <input type="number" id="end-page" name="end-page" min="1" max="1" value="1">
          </div>
          <div class="slider-box">
            <label for="n_cards_slider">Amount of Cards</label>
            <input type="range" min="5" max="75" value="40" step="5" class="slider" id="n_cards_slider" name="n_cards">
            <p id="n_cards"></p>
          </div>
          <label for="prompt">Specify Focus</label>
          <textarea name="prompt" id="file-prompt" placeholder="Further specify the focus of the deck..."></textarea>
          <input type="submit" value="Generate deck" class="button">
        </form>
      </div>
      <a class="back-button" href="{{ url_for('decks.index') }}"> <!-- TODO: Add go back thing here -->
        <i class="fa-solid fa-arrow-left"></i>
      </a>
    </div>
  </div>
  <script src="{{ url_for('static', filename='scripts/cardrange_slider.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/upload_file.js') }}"></script>
{% endblock %}

application/templates/generate_deck/from_prompt.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Generate deck{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="deck-page">
    <div class="newdeck-editor-box-outer">
      <div class="newdeck-editor-box">
        <form class="generate-form" method="post" action="{{url_for('generate_deck.generate_deck_begin') }}">
            <h2>Prompt</h2>
            <textarea name="prompt" id="" placeholder="Enter a prompt..."></textarea>
            <h2>Focus Areas</h2>
            <div class="focus-boxes">
                <input type="checkbox" name="focus_areas" value="dates" id="dates">
                <label for="dates">Dates</label>
                <input type="checkbox" name="focus_areas" value="names" id="names">
                <label for="names">Names</label>
            </div>
            <h2>Number of Cards</h2>
            <div class="quantity-boxes">
                <input type="radio" class="button" name="quantity" value="few" id="few">
                <label for="few">Few</label>
                <input type="radio" class="button" name="quantity" value="medium" id="medium" checked>
                <label for="medium">Medium</label>
                <input type="radio" class="button" name="quantity" value="many" id="many">
                <label for="many">Many</label>
            </div>
            <button type="submit" value="generate-deck" class="button">Generate Deck</button>
        </form>
      </div>
      <a class="back-button" href="{{ url_for('decks.index') }}">
        <i class="fa-solid fa-arrow-left"></i>
      </a>
    </div>
  </div>
{% endblock %}