application/models/deck.py
from datetime import datetime
from .base import db

class Deck(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(500), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    cards = db.relationship('Card', backref='deck', lazy=True, cascade='all, delete-orphan')

    def __repr__(self):
        return f'<Deck {self.id}, {self.name}>'

application/routes/card_editor.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from flask_login import login_required, current_user

from application.handlers import Cardhandler

# Create blueprint for deck views
bp = Blueprint('card_editor', __name__)

""" ---------- Routes ---------- """

@bp.route('/card_editor/card_delete/<int:card_id>', methods=('GET', 'POST'))
@login_required
def card_delete(card_id: int):
    card = Cardhandler.get_card(card_id)
    deck_id = card.deck_id
    Cardhandler.delete_card(card_id)
    return redirect(url_for('deck_editor.deck_editor', deck_id=deck_id))

@bp.route('/card_editor/card_save/<int:card_id>', methods=('GET', 'POST'))
@login_required
def card_save(card_id: int):
    front = request.form.get('front')
    back = request.form.get('back')
    deck_id = request.form.get('deck_id')
    Cardhandler.set_card_front(front, card_id)
    Cardhandler.set_card_back(back, card_id)
    return redirect(url_for('deck_editor.deck_editor', deck_id=deck_id))

@bp.route('/card_editor/card_editor/<int:card_id>', methods=('GET', 'POST'))
@login_required
def card_editor(card_id):
    # Card can't be loaded
    if not card_id:
        flash('The card cannot be loaded')
        return redirect(url_for('decks.index'))
    # Card does not belong to current user
    if not Cardhandler.is_owned_by(current_user, card_id):
        flash("You don't have permission to edit this card")
        return redirect(url_for('decks.index'))
    # Load card
    card = Cardhandler.get_card(card_id)
    return render_template('decks/card_editor.html', card=card)

@bp.route('/card_editor/new_card/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def new_card(deck_id):
    if not deck_id:
        flash('NO DECK ID! WARNING')
    # Create new card
    card_id = Cardhandler.new_card(deck_id)
    card = Cardhandler.get_card(card_id)
    return render_template('decks/card_editor.html', card=card)

application/routes/deck_editor.py
"""
    This file contains all views for editing a deck.
"""

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from flask_login import login_required, current_user

from application.handlers import Cardhandler, Deckhandler

from application.routes.page_stack import PageStack

# Create blueprint for deck views
bp = Blueprint('deck_editor', __name__)

""" ---------- Routes ---------- """

@bp.route('/deck_editor/deck_delete/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def deck_delete(deck_id: int):
    Deckhandler.delete_deck(deck_id)
    flash('Deck deleted succesfully')
    return redirect(url_for('decks.index'))

@bp.route('/deck_editor/deck_save/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def deck_save(deck_id: int):
    name = request.form.get('name')
    description = request.form.get('description')
    Deckhandler.update_deck(name, description, deck_id)
    flash('Deck saved succesfully')
    return redirect(url_for('decks.index'))

@bp.route('/deck_editor/deck_editor/<int:deck_id>', methods=('GET', 'POST')) 
@login_required
def deck_editor(deck_id: int):
    # Deck can't be loaded
    if not deck_id:
        flash('The deck cannot be loaded')
        return redirect(url_for('decks.index'))
    # Deck does not belong to current user
    if not Deckhandler.is_owned_by(current_user, deck_id):
        flash("You don't have permission to edit this deck")
        return redirect(url_for('decks.index'))
    # Load deck
    deck = Deckhandler.get_deck(deck_id)
    cards = Cardhandler.get_cards(deck_id)
    return render_template('decks/deck_editor.html', deck=deck, cards=cards)

@bp.route('/deck_editor/new_deck/', methods=('GET', 'POST')) 
@login_required
def new_deck():
    # Create new deck
    deck_id = Deckhandler.new_deck(current_user)
    deck = Deckhandler.get_deck(deck_id)
    cards = Cardhandler.get_cards(deck_id)  # Will always be empty
    return render_template('decks/deck_editor.html', deck=deck, cards=cards)

application/routes/decks.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from flask_login import login_required, current_user

from application.handlers import Deckhandler
from application.routes.page_stack import PageStack

# Create blueprint for deck views
bp = Blueprint('decks', __name__)

# A simple start page
@PageStack.stack_page
@bp.route('/')
def home():
    return redirect(url_for('decks.index'))

@PageStack.stack_page
@bp.route('/decks', methods=('GET', 'POST'))
@login_required
def index():
    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        Deckhandler.add_deck(name, description, current_user)

    decks = Deckhandler.get_decks(current_user)
    return render_template('decks/index.html', decks=decks)

application/routes/generate_deck.py
"""
    This file contains all views for generating a deck.
"""

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, jsonify
)
from flask_login import login_required, current_user

from application.handlers import Cardhandler, Deckhandler
from application.gpt import gpt_generate_deck
from application.engine import pdf_reader
from application.engine.handle_markdown import markdown_to_html

# Create blueprint for deck views
bp = Blueprint('generate_deck', __name__)

""" ---------- Helpers ---------- """

def dict_to_deck(deck_dict, user):
    """ Create a deck from a dict. Returns deck id """
    name = deck_dict.get('name')
    desc = deck_dict.get('description')
    questions = deck_dict.get('questions')
    answers = deck_dict.get('answers')
    deck_id = Deckhandler.add_deck(name, desc, user)
    Cardhandler.create_cards(questions, answers, deck_id)
    return deck_id

def get_extension(filename: str) -> str:
    return filename.rsplit('.', 1)[1].lower()

def is_pdf(filename: str) -> bool:
    if not '.' in filename: return False
    return get_extension(filename) == 'pdf'

def is_markdown(filename: str) -> bool:
    if not '.' in filename: return False
    return get_extension(filename) == 'md'

def is_txt(filename: str) -> bool:
    if not '.' in filename: return False
    return get_extension(filename) == 'txt'

""" ---------- Routes ---------- """

@bp.route('/generate_deck/deck_from_file/', methods=('GET', 'POST'))
@login_required
def deck_from_file():
    # Get input
    file = request.files['file']
    n_cards = int(request.form.get('n_cards'))
    prompt = request.form.get('prompt')
    start_page = int(request.form.get('start-page'))
    end_page = int(request.form.get('end-page'))
    # Decode file content
    if is_pdf(file.filename):
        text = pdf_reader.extract_text(file, start_page, end_page)
    elif is_markdown(file.filename) or is_txt(file.filename):
        file_content = file.read()
        text = file_content.decode('utf-8')
    else:
        flash('Invalid file')
        return redirect(url_for('generate_deck.from_file'))
    # Generate deck
    raw_deck = gpt_generate_deck(text, n_cards, [prompt])
    if not raw_deck:
        flash('There was an error trying to generate your deck.')
        return redirect(url_for('decks.index'))
    deck_id = Deckhandler.add_deck(name=raw_deck.get('name'), description=raw_deck.get('description'), user=current_user)
    for question, answer in zip(raw_deck.get('questions'), raw_deck.get('answers')):
        # Convert markdown to html
        if is_markdown(file.filename):
            question = markdown_to_html(question)
            answer = markdown_to_html(answer)
        Cardhandler.add_card(question, answer, deck_id)
    return redirect(url_for('decks.index'))

@bp.route('/generate_deck/number_of_pdf_pages', methods=['POST'])
def get_number_of_pdf_pages():
    # Check if request correct with file
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400
    # Check if file selected
    file = request.files['file']
    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400
    # Get page range if is pdf
    if file and is_pdf(file.filename):
        page_range = pdf_reader.get_page_range(file)
        return jsonify({"page_range": page_range})
    return jsonify({"error": "Not pdf"}), 400

@bp.route('/generate_deck/cards_from_desc/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def cards_from_desc(deck_id):
    # Save deck
    name = request.form.get('name')
    description = request.form.get('description')
    Deckhandler.update_deck(name, description, deck_id)
    # Generate cards
    raw_deck = gpt_generate_deck(description)
    if not raw_deck:
        flash('There was an error trying to generate your cards.')
        return redirect(url_for('deck_editor.deck_editor', deck_id=deck_id))
    for question, answer in zip(raw_deck.get('questions'), raw_deck.get('answers')):
        Cardhandler.add_card(question, answer, deck_id)
    
    deck = Deckhandler.get_deck(deck_id)
    return redirect(url_for('deck_editor.deck_editor', deck_id=deck.id))

@bp.route('/generate_deck/from_prompt')
@login_required
def from_prompt():
    return render_template('/generate_deck/from_prompt.html')

@bp.route('/generate_deck/from_file')
@login_required
def from_file():
    return render_template('generate_deck/from_file.html')

@bp.route('/generate_deck/generate_deck_begin', methods=('GET', 'POST'))
@login_required
def generate_deck_begin():
    quantities = {
        'few': 10,
        'medium': 25,
        'many': 50
    }
    prompt = request.form.get('prompt')
    focus_areas = request.form.getlist('focus_areas')
    quantity = request.form.get('quantity')
    n_cards = quantities[quantity]
    raw_deck = gpt_generate_deck(prompt, n_cards, focus_areas)
    if not raw_deck:
        flash('There was an error trying to generate your deck.')
        return redirect(url_for('decks.index'))
    deck_id = dict_to_deck(raw_deck, current_user)
    flash('Deck generated successfully')
    return redirect(url_for('deck_editor.deck_editor', deck_id=deck_id))

application/routes/play.py
"""
    This file contains all views for playing a deck.
"""

import random
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from flask_login import login_required

from application.handlers import Cardhandler, Deckhandler

# Create blueprint for deck views
bp = Blueprint('play', __name__)

# Keeps the deck's card while in a play-through
card_ids = []
# Used to keep track of the progress of the play-through
n_cards_played = 0

class PlayThrough:
    ''' A class representing a playthrough of a deck. '''

    def __init__(self, deck_id):
        self.deck_id = deck_id
        self.card_ids = [card.id for card in Cardhandler.get_cards(deck_id)]
        random.shuffle(self.card_ids)
        self.n_cards_played = 0
        self.n_total_cards = len(self.card_ids)
    
    def next_card(self):
        if len(self.card_ids) == 0:
            return None
        self.n_cards_played += 1
        return self.card_ids.pop()
    

# Global playthrough
playthrough = None

@bp.route('/play/init_play_all/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def init_play_all(deck_id):
    # global card_ids
    # card_ids = [card.id for card in Cardhandler.get_cards(deck_id)]
    # random.shuffle(card_ids)
    global playthrough
    playthrough = PlayThrough(deck_id)

    return redirect(url_for('play.play_new_card', deck_id=deck_id))

@bp.route('/play/play_new_card/<int:deck_id>')
@login_required
def play_new_card(deck_id):
    
    # Get card and increase number of cards played
    card_id = playthrough.next_card()
    if not card_id:
        return redirect(url_for('play.play_end', deck_id=deck_id))

    n_cards_played = playthrough.n_cards_played
    n_total_cards = playthrough.n_total_cards

    return redirect(url_for(
        'play.play_card_front',
        card_id=card_id,
        n_cards_played=n_cards_played,
        n_total_cards=n_total_cards
    ))

@bp.route('/play/play_card_front/<int:card_id>/<int:n_cards_played>/<int:n_total_cards>', methods=('GET', 'POST'))
@login_required
def play_card_front(card_id, n_cards_played, n_total_cards):
    print(card_id)
    card = Cardhandler.get_card(card_id)
    return render_template('decks/play_card_front.html', card=card, n_cards_played=n_cards_played, n_total_cards=n_total_cards)

@bp.route('/play/play_card_back/<int:card_id>/<int:n_cards_played>/<int:n_total_cards>', methods=('GET', 'POST'))
@login_required
def play_card_back(card_id, n_cards_played, n_total_cards):
    card = Cardhandler.get_card(card_id)
    return render_template('decks/play_card_back.html', card=card, n_cards_played=n_cards_played, n_total_cards=n_total_cards)

@bp.route('/play/play_end/<int:deck_id>', methods=('GET', 'POST'))
@login_required
def play_end(deck_id):
    deck = Deckhandler.get_deck(deck_id)
    return render_template('decks/play_end.html', deck=deck)

application/templates/decks/card_editor.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Edit Card{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="page">
    <div class="card-editor-box">
      <!-- Edit current information -->
      <form method="post" action="{{ url_for('card_editor.card_save', card_id=card.id) }}">
          <input type="hidden" name="deck_id" value="{{ card.deck_id }}">
          <input type="hidden" name="id" value="{{ card.id }}">
          <h2>Question</h2>
          <textarea name="front" placeholder="Add a frontside...">{{card.question}}</textarea>
          <h2>Answer</h2>
          <textarea name="back" placeholder="Add a backside...">{{ card.answer }}</textarea>
          <div class="deck-actions">
            <a href="{{ url_for('card_editor.card_delete', card_id=card.id) }}" class="button delete-btn">Delete</a>
            <button type="submit" name="action" value="save-card" class="button">Save</button>
          </div>
      </form>
    </div>
    <a class="back-button" href="{{ url_for('deck_editor.deck_editor', deck_id=card.deck_id) }}">
      <i class="fa-solid fa-arrow-left"></i>
    </a>
  </div>
{% endblock %}

application/templates/decks/cardeditor.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Edit Card{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="card-editor">
    <!-- Edit current information -->
    <form method="post" action="{{ url_for('decks.card_save', card_id=card.id) }}">
        <input type="hidden" name="deck_id" value="{{card.get('deck_id')}}">
        <input type="hidden" name="id" value="{{card.get('id')}}">
        <h2>Question</h2>
        <textarea name="front" id="card-front" placeholder="Add a frontside...">{{card.get('front')}}</textarea>
        <h2>Answer</h2>
        <textarea name="back" id="card-back" placeholder="Add a backside...">{{ card.get('back') }}</textarea>
        <div class="deck-actions">
          <a href="{{ url_for('decks.card_delete', card_id=card.id) }}" class="btn delete-btn">Delete</a>
          <button type="submit" name="action" value="save-card" class="btn">Save</button>
        </div>
    </form>
  </div>
{% endblock %}

application/templates/decks/deck_editor.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}New deck{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="deck-page">
      <div class="newdeck-editor-box-outer">
        <div class="newdeck-editor-box">
          <!-- Edit current information -->
          <form method="post" action="{{ url_for('deck_editor.deck_save', deck_id=deck.id) }}" class="deck-info">
              <input type="hidden" name="id" value="{{deck.id}}">
              <input type="text" name="name" id="deck-name" placeholder="Name" value="{{ deck.name }}">
              <textarea name="description" id="deck-description" placeholder="Add a description...">{{ deck.description }}</textarea>
              <div class="deck-actions">
                <a href="{{ url_for('deck_editor.deck_delete', deck_id=deck.id) }}" class="button delete-btn">Delete</a>
                <a href="#" class="button generate-btn" onclick="submitGenerateForm()">Generate</a>
                <button type="submit" name="action" value="save-deck" class="button">Save</button>
              </div>
          </form>
        </div>
        <a class="back-button" href="{{ url_for('decks.index') }}"> <!-- TODO: Add go back thing here -->
          <i class="fa-solid fa-arrow-left"></i>
        </a>
      </div>
      <div class="cardview">
        <!-- <h2>Cards</h2> -->
        <ul class="cards">
          <!-- Add new card -->
          <a class="card-link" href="{{ url_for('card_editor.new_card', deck_id=deck.id) }}">
            <div class="card add-card">
              <div class="plus-symbol">+</div>
            </div>
          </a>
          <!-- Show all cards -->
          {% for card in cards: %}
            <li class="card">
              <div class="card-inner">
                <div class="card-front">
                  <p class="card-title">Question</p>
                  <p class="card-text">{{ card.question }}</p>
                </div>
                <div class="card-back">
                  <p class="card-title">Answer</p>
                  <p class="card-text">{{ card.answer }}</p>
                </div>
              </div>
              <a class="edit-button" href="{{ url_for('card_editor.card_editor', card_id=card.id, deck_id=deck.id) }}">
                <i class="fas fa-pencil-alt"></i>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    
  <!-- To make the card rotate on press -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const cards = document.querySelectorAll('.card');

      cards.forEach(function(card) {
          card.addEventListener('click', function() {
              this.classList.toggle('is-flipped'); // Use 'this' to refer to the clicked card
          });
      });
    });

    function submitGenerateForm() {
      var form = document.querySelector('.deck-info');
      form.action = "{{ url_for('generate_deck.cards_from_desc', deck_id=deck.id) }}";
      form.submit();
    }
  </script>
{% endblock %}

application/templates/decks/editor.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}New deck{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="newdeck-editor">
    <!-- Edit current information -->
    <form method="post" action="{{ url_for('decks.deck_save', deck_id=deck.id) }}" class="deck-info">
        <input type="hidden" name="id" value="{{deck.get('id')}}">
        <input type="text" name="name" id="deck-name" placeholder="Name" value="{{ deck.get('name', '') }}">
        <textarea name="description" id="deck-description" placeholder="Add a description...">{{ deck.get('description') }}</textarea>
        <div class="deck-actions">
          <a href="{{ url_for('decks.deck_delete', deck_id=deck.id) }}" class="btn delete-btn">Delete</a>
          <button type="submit" name="action" value="save-deck" class="btn">Save</button>
        </div>
    </form>

    <div class="cardview">
      <h2>Cards</h2>
      <ul class="cards">
        <!-- Add new card -->
        <a class="card-link" href="{{ url_for('decks.cardeditor', deck_id=deck.id) }}">
          <div class="card add-card">
            <div class="plus-symbol">+</div>
          </div>
        </a>
        <!-- Show all cards -->
        {% for card in cards: %}
        <a class="card-link" href="{{ url_for('decks.cardeditor', deck_id=deck.id, card_id=card.id) }}">
          <li class="card">
            <div class="front">
              <p>{{card.front}}</p>
            </div>
            <div class="back">
              <p><p>{{card.back}}</p></p>
            </div>
          </li>
        </a>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

application/templates/decks/index.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Decks{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div id="deckviewer">
    <!-- Add new deck -->
    <div class="deck-box" id="add-deck">
      <div class="deck-box-inner">
        <div class="plus-symbol">+</div>
      </div>
      <div class="play-deck-buttons">
        <a href="{{ url_for('deck_editor.new_deck') }}" class="button">Create New</a>
        <a href="{{ url_for('generate_deck.from_prompt')}}" class="button">Generate From Prompt</a>
        <a href="{{ url_for('generate_deck.from_file')}}" class="button">Generate From File</a>
      </div>
    </div>
    <!-- Show all decks -->
    {% for deck in decks: %}
    <div class="deck-box">
      <div class="deck-box-inner">
        <h4 class="deck-name">{{ deck['name'] }}</h4>
        <p class="deck-description">{{ deck['description'] }}</p>
      </div>
      <div class="play-deck-buttons">
        <a href="{{ url_for('play.init_play_all', deck_id=deck.id) }}" class="button">Practice</a>
        <a href="{{ url_for('play.init_play_all', deck_id=deck.id) }}" class="button">Play All</a>
      </div>
      <a class="edit-button" href="{{ url_for('deck_editor.deck_editor', deck_id=deck.id) }}">
        <i class="fas fa-pencil-alt"></i>
      </a>
    </div>
    {% endfor %}
  </div>
{% endblock %}

application/templates/decks/play_card_back.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Play{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="play-card-page">
    <p>{{n_cards_played}} of {{n_total_cards}} cards played</p>
    <div class="play-card-container">
      <p>Answer</p>
      <div class="play-card-text">
        <p>{{ card.answer }}</p>
      </div>
      <div class="play-card-actions">
        <a href="{{ url_for('play.play_card_front', card_id=card.id, n_cards_played=n_cards_played, n_total_cards=n_total_cards) }}" class="button">Show Question</a>
        <a href="{{ url_for('play.play_new_card', deck_id=card.deck_id) }}" class="button">Next Card</a>
      </div>
    </div>
  </div>
{% endblock %}

application/templates/decks/play_card_front.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Play{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="play-card-page">
    <p>{{n_cards_played}} of {{n_total_cards}} cards played</p>
    <div class="play-card-container">
      <p>Question</p>
      <div class="play-card-text">
        <p>{{ card.question }}</p>
      </div>
      <div class="play-card-actions">
        <a href="{{ url_for('play.play_card_back', card_id=card.id, n_cards_played=n_cards_played, n_total_cards=n_total_cards) }}" class="button">Show Answer</a>
      </div>
    </div>
  </div>
{% endblock %}

application/templates/decks/play_end.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Play{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="card-editor">
    <h2>End of deck</h2>
    <div class="deck-actions">
      <a href="{{ url_for('play.init_play_all', deck_id=deck.id) }}" class="button">Play again</a>
      <a href="{{ url_for('decks.index') }}" class="button">Return to Decks</a>
    </div>
  </div>
{% endblock %}